<?php

const COMMAND_TYPE_TOKEN_COIN_PAIR = 18;
const COMMAND_TYPE_DELETE_FAILED_JOBS = 27;

const BOT_SYNC_MARKET_PRICE = 'neutral';
const BOT_INCREASE_MARKET_PRICE = 'increase';
const BOT_DECREASE_MARKET_PRICE = 'decrease';
const BOT_RANDOM_MARKET_PRICE = 'random';

const RATE_SOURCE_DEFAULT = 'default';
const RATE_SOURCE_DB = 'rate_db';
const RATE_SOURCE_EXTERNAL = 'external';

const PERCENT_LEFT_LEN = 1;
const PERCENT_DECIMAL = 3;
const MAX_PERCENT = 10;
const MIN_PERCENT = 0.01;

const BOT_ORDER_PROCESS_REDIS = 2;
const BOT_ORDER_PROCESS_DIRECT_COMMAND = 1;
const MATIC_TOKEN = 44;